name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout source'
        uses: actions/checkout@v3
      - name: 'Install Nix Flakes'
        uses: cachix/install-nix-action@v20
      - name: 'Setup Cachix'
        uses: cachix/cachix-action@v12
        with:
          name: wurzelpfropf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN_PUBLIC }}'
      - name: 'Build default package'
        run: nix build -L .

  check:
    name: 'Check'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Checkout source'
        uses: actions/checkout@v2
      - name: 'Install Nix Flakes (nixos-test, recursive-nix)'
        uses: cachix/install-nix-action@v20
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes recursive-nix
            system-features = nixos-test benchmark big-parallel kvm recursive-nix
      - name: 'Setup Cachix'
        uses: cachix/cachix-action@v12
        with:
          name: wurzelpfropf
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN_PUBLIC }}'
      - name: 'Run all checks'
        run: nix flake check -L .
